### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by yimwy** [nitzanlab/scPrisma#3]
Hi, I am interested in performing circadian single cell analysis using scPrisma but is very unfamiliar with python codes. I received the following error at linear filtering and unable to proceed. I started with a .h5ad file with a single cell cluster with 6 time points as following: 

 adata = sc.read_h5ad("mice.h5ad")
 adata.obs['zt'] = adata.obs['zt'].astype('str')
 adata = scPrisma.algorithms.sort_data_crit(adata=copy.deepcopy(adata.copy()), crit='zt', crit_list=['0','1','2','3','4','5']) #sort the dataaccording to the timepoints

[](url)
![Screenshot from 2023-05-11 10-24-27](https://github.com/nitzanlab/scPrisma/assets/62978638/1f183799-fe3e-47ef-8579-6084a8956b90)

**Comment by JonathanKarin** [comment]
Hi,
Thank you for this question.
The function filter_linear_full should get as an input numpy matrix, therefore you can use "adata_linear_filtered.X.toarray()". We will fix this issue in the next version.
Pay attention that 'filter_linear_full' is a linear filtering algorithm- removing a linear (and not circular) component from the data.
Jonathan
